# Generated by Django 3.2.5 on 2021-11-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('task', models.CharField(max_length=100)),
                ('starts_from', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('done', models.BooleanField()),
            ],
        ),
    ]
