# Generated by Django 3.2.5 on 2021-11-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
